<script setup lang="ts">
import type { Link, LinkRequest } from "@/api";
import type { ResponseError } from "@/api";
import type { Ref } from "vue";
import { reactive, ref } from "vue";
import { VForm } from "vuetify/components";
import { useLinkStore } from "@/stores";
import { useLinksApi } from "@/api";

const emit = defineEmits<{
  (e: "created", link: Link): void;
  (e: "cancel"): void;
}>();

const store = useLinkStore();
const api = useLinksApi();
const form = ref<VForm>();

const linkData: LinkRequest = reactive({
  _short: "",
  target: "",
  login_required: false,
});
const apiErrors: Ref<Record<string, string[]>> = ref({});

async function onFormSubmit() {
  if ((await form.value!.validate()).valid) {
    if (linkData._short === "") {
      linkData._short = undefined;
    }

    try {
      const newLink = await api.value!.linksCreate({
        linkRequest: linkData,
      });
      store.add(newLink);
      emit("created", newLink);
    } catch (e) {
      const error = e as ResponseError;
      apiErrors.value = await error.response.json();
    }
  }
}
</script>

<template>
  <v-card>
    <v-card-title>Create New Shortlink</v-card-title>
    <v-form ref="form" @submit.prevent="onFormSubmit">
      <v-container>
        <v-row>
          <!-- Short -->
          <v-col :cols="12">
            <v-text-field
              id="short"
              label="Short (optional)"
              hint="The short url part (will be autogenerated if left empty)"
              v-model="linkData._short"
              variant="underlined"
              :error-messages="apiErrors['short']"
              @update:modelValue="apiErrors['short'] = []"
            />
          </v-col>

          <!-- Target -->
          <v-col :cols="12">
            <v-text-field
              id="target"
              label="Destination"
              hint="Where the shortlink leads"
              placeholder="https://example.com/"
              v-model="linkData.target"
              variant="underlined"
              :error-messages="apiErrors['target']"
              @update:modelValue="apiErrors['target'] = []"
            />
          </v-col>

          <!-- Login required? -->
          <v-col :cols="12">
            <v-checkbox
              id="login_required"
              label="Login required?"
              v-model="linkData.loginRequired"
              :error-messages="apiErrors['loginRequired']"
              @update:modelValue="apiErrors['loginRequired'] = []"
            />
          </v-col>
        </v-row>
      </v-container>

      <v-card-actions>
        <v-btn variant="outlined" prepend-icon="mdi-cancel" @click="emit('cancel')">Cancel</v-btn>
        <v-btn color="primary" variant="flat" prepend-icon="mdi-content-save" type="submit">Save</v-btn>
      </v-card-actions>
    </v-form>
  </v-card>
</template>

<style scoped></style>
