<script setup lang="ts">
import type { LinkRequest } from "@/api";
import { reactive, ref } from "vue";
import { VForm } from "vuetify/components";

const emit = defineEmits<{
  (e: "submit", linkData: LinkRequest): void;
  (e: "cancel"): void;
}>();

const form = ref<VForm>();
const targetValidationRules = [(v: string) => (!!v && v.length > 0) || "Target is required"];

const linkData: LinkRequest = reactive({
  _short: "",
  target: "",
});

async function onFormSubmit() {
  if ((await form.value!.validate()).valid) {
    if (linkData._short === "") {
      linkData._short = undefined;
    }

    emit("submit", linkData);
  }
}
</script>

<template>
  <v-form ref="form" @submit.prevent="onFormSubmit">
    <v-container>
      <v-row>
        <!-- Short -->
        <v-col :cols="12">
          <v-text-field
            label="Short (optional)"
            v-model="linkData._short"
            variant="underlined"
            placeholder="The short url part (will be autogenerated if left empty)"
          />
        </v-col>

        <!-- Target -->
        <v-col :cols="12">
          <v-text-field
            label="Destination"
            v-model="linkData.target"
            variant="underlined"
            :rules="targetValidationRules"
            placeholder="Where to redirect to"
          />
        </v-col>
      </v-row>
    </v-container>

    <v-card-actions>
      <v-btn variant="outlined" prepend-icon="mdi-cancel" @click="emit('cancel')">Cancel</v-btn>
      <v-btn color="primary" variant="flat" prepend-icon="mdi-content-save" type="submit">Save</v-btn>
    </v-card-actions>
  </v-form>
</template>

<style scoped></style>
