---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: mafiasi-link-shortener
resources:
  - k8s/deployment.yml
  - k8s/service.yml
configMapGenerator:
  - name: config
