/* tslint:disable */
/* eslint-disable */
/**
 * Mafiasi Link Shortener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ag-server@informatik.uni-hamburg.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PatchedLinkRequest
 */
export interface PatchedLinkRequest {
    /**
     *
     * @type {string}
     * @memberof PatchedLinkRequest
     */
    _short?: string;
    /**
     *
     * @type {string}
     * @memberof PatchedLinkRequest
     */
    target?: string;
}

/**
 * Check if a given object implements the PatchedLinkRequest interface.
 */
export function instanceOfPatchedLinkRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedLinkRequestFromJSON(json: any): PatchedLinkRequest {
    return PatchedLinkRequestFromJSONTyped(json, false);
}

export function PatchedLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedLinkRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        '_short': !exists(json, 'short') ? undefined : json['short'],
        'target': !exists(json, 'target') ? undefined : json['target'],
    };
}

export function PatchedLinkRequestToJSON(value?: PatchedLinkRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'short': value._short,
        'target': value.target,
    };
}
