---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafiasi-link-shortener
spec:
  selector:
    matchLabels: {}
  template:
    spec:
      containers:
        - name: mafiasi-link-shortener
          image: registry.mafiasi.de/mafiasi_link_shortener
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secret
          ports:
            - containerPort: 8000
              name: http
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 45
          readinessProbe:
            tcpSocket:
              port: http
