# Generated by Django 3.1.5 on 2021-01-18 13:35

from django.db import migrations, models

import mafiasi_link_shortener.links.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "short",
                    models.CharField(
                        db_index=True,
                        default=mafiasi_link_shortener.links.models.link_default_short,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target", models.URLField()),
            ],
        ),
    ]
