# Generated by Django 4.1.4 on 2023-03-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_alter_mafiasiuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="target",
            field=models.URLField(max_length=500),
        ),
    ]
