# Generated by Django 4.1.4 on 2023-06-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_increase_link_target_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="login_required",
            field=models.BooleanField(default=False),
        ),
    ]
