/* tslint:disable */
/* eslint-disable */
/**
 * Mafiasi Link Shortener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ag-server@informatik.uni-hamburg.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface RootRetrieveRequest {
    _short: string;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async rootRetrieveRaw(requestParameters: RootRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters._short === null || requestParameters._short === undefined) {
            throw new runtime.RequiredError('_short','Required parameter requestParameters._short was null or undefined when calling rootRetrieve.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/{short}`.replace(`{${"short"}}`, encodeURIComponent(String(requestParameters._short))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async rootRetrieve(requestParameters: RootRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rootRetrieveRaw(requestParameters, initOverrides);
    }

}
