"""
Django settings for mafiasi_link_shortener project.

Generated by "django-admin startproject" using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from configurations import Configuration, values
from django_auth_mafiasi.configuration import BaseAuthConfigurationMixin, DevAuthConfigurationMixin

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


class Base(BaseAuthConfigurationMixin, Configuration):
    # Application definition
    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "links",
    ] + BaseAuthConfigurationMixin.MAFIASI_AUTH_APPS

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]

    ROOT_URLCONF = "mafiasi_link_shortener.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "mafiasi_link_shortener.wsgi.application"

    # Database
    # https://docs.djangoproject.com/en/3.1/ref/settings/#databases

    @property
    def DATABASES(self):
        return {
            "default": {
                "ENGINE": "django.db.backends.postgresql_psycopg2",
                "HOST": self.DB_HOST,
                "PORT": self.DB_PORT,
                "USER": self.DB_USER,
                "PASSWORD": self.DB_PASSWORD,
                "NAME": self.DB_NAME,
            }
        }

    # Password validation
    # https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/3.1/topics/i18n/

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "Europe/Berlin"

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/3.1/howto/static-files/

    STATIC_URL = "/static/"

    # Configurable properties
    SECRET_KEY = values.SecretValue()
    DEBUG = values.BooleanValue(default=False)
    ALLOWED_HOSTS = values.ListValue(environ_required=True)
    DB_HOST = values.Value(environ_required=True)
    DB_PORT = values.Value(default=5432)
    DB_USER = values.Value(default="mafiasi_link_shortener")
    DB_PASSWORD = values.SecretValue()
    DB_NAME = values.Value(default="mafiasi_link_shortener")
    LINK_SHORT_LENGTH = values.IntegerValue(default=6)


class Dev(DevAuthConfigurationMixin, Base):
    SECRET_KEY = values.Value(default="q@26c)#%lxzh0ip6bs--eeg9pz+80+yefn5zc)lxf_&!c#1c(2")
    DEBUG = values.BooleanValue(default=True)
    ALLOWED_HOSTS = values.ListValue(default=["localhost", "127.0.0.1"])
    DB_HOST = values.Value(default="localhost")
    DB_PASSWORD = values.Value(default="mafiasi_link_shortener")

    INSTALLED_APPS = Base.INSTALLED_APPS + ["debug_toolbar"]
    MIDDLEWARE = Base.MIDDLEWARE + ["debug_toolbar.middleware.DebugToolbarMiddleware"]
    INTERNAL_IPS = [
        "127.0.0.1"
    ]
