/* tslint:disable */
/* eslint-disable */
/**
 * Mafiasi Link Shortener
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ag-server@informatik.uni-hamburg.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
} from './Link';

/**
 *
 * @export
 * @interface PaginatedLinkList
 */
export interface PaginatedLinkList {
    /**
     *
     * @type {number}
     * @memberof PaginatedLinkList
     */
    count?: number;
    /**
     *
     * @type {string}
     * @memberof PaginatedLinkList
     */
    next?: string | null;
    /**
     *
     * @type {string}
     * @memberof PaginatedLinkList
     */
    previous?: string | null;
    /**
     *
     * @type {Array<Link>}
     * @memberof PaginatedLinkList
     */
    results?: Array<Link>;
}

/**
 * Check if a given object implements the PaginatedLinkList interface.
 */
export function instanceOfPaginatedLinkList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedLinkListFromJSON(json: any): PaginatedLinkList {
    return PaginatedLinkListFromJSONTyped(json, false);
}

export function PaginatedLinkListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLinkList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(LinkFromJSON)),
    };
}

export function PaginatedLinkListToJSON(value?: PaginatedLinkList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(LinkToJSON)),
    };
}
