name: deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build-container:
    uses: fsinfuhh/workflows/.github/workflows/build_image.yml@main

  deploy:
    needs: [ build-container ]
    uses: fsinfuhh/workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      app_path: k8s/apps/mafiasi/link-shortener
      image_name: ${{ needs.build-container.outputs.image_name }}
      new_digest: ${{ needs.build-container.outputs.image_digest }}
